---
- hosts: all
  become: true
  tasks:
   - name: stop docker container in ansible server
     command: docker stop  simple-devops-container
     ignore_errors: yes

   - name: remove docker container from ansible server
     command: docker rm -f simple-devops-container
     ignore_errors: yes
   - name: remove docker images from ansible server
     command: docker rmi-f vdbsrao/simple-devops-image
     ignore_errors: yes

   - name: pull image  from  dockerhub
     command: docker pull vdbsrao/simple-devops-image

   - name: building container out of image
     command: docker run -d --name  simple-devop-container -p 8090:8080  
     vdbsrao/simple-devops-image


