---
- hosts: all
  become: false
  tasks:
   - name: stop docker container in ansible server
     command: docker stop  simple-devops-image
     ignore_errors: yes

   - name: remove docker container from ansible server
     command: docker rm -f simple-devops-image
     ignore_errors: yes
   - name: remove docker images from ansible server
     command: docker rmi-f simple-devops-image
     ignore_errors: yes

   - name: creating docker image
     command: docker build -t simple-devops-image .
     args:
       chdir: /opt/docker
   - name: adding tag to docker image
     command: docker tag simple-devops-image vdbsrao/simple-devops-image


   - name: push image  to dockerhub
     command: docker push vdbsrao/simple-devops-image


   - name: removing images in local server
     command: docker rmi simple-devops-image vdbsrao/simple-devops-image
     ignore_errors: yes

