---
- hosts: ansibleserver
  become: true

  tasks:
  - name: create docker image using war file
    command: docker build -t simple-devops-image .
    args:
      chdir: /opt/kubernetes

  - name: create tag to image
    command: docker tag simple-devops-image vdbsrao/simple-devops-image
             
  - name: push image on to dockerhub
    command: docker push vdbsrao/simple-devops-image

#  - name: remove docker images form ansible server
#    command: docker rmi tomcat simple-devops-image:latest vdbsrao/simple-devops-image
#    ignore_errors: yes
